services:
  db:
    image: postgres:17.2
    container_name: chats_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXT_PORT}:5432"
    volumes:
      - ./db_folder:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    container_name: chats_api
    ports:
      - "8011:8000"
    command: >
      bash -c
      "alembic upgrade head && python main.py"
    environment:
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_folder:

