services:
  db:
    image: postgres:17.2
    container_name: chats_db
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - ./db_folder:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    container_name: chats_api
    ports:
      - "8011:8000"
    command: >
      bash -c
      "alembic upgrade head && python main.py"
    environment:
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_folder:

